### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by benoror** [Glavin001/ember-jsoneditor#13]
Hi @Glavin001!

Not sure if this is a bug or a mistake from my side. I'm getting a **Route error the 2nd time** I access the route, where I [render the JSONEditor in the route's template](https://github.com/benoror/ember-postgrest-dynamic-ui/blob/master/tests/dummy/app/templates/form.hbs#L6). I'm [fetching the JSON data from the Route's model](https://github.com/benoror/ember-postgrest-dynamic-ui/blob/master/tests/dummy/app/routes/form.js#L16)

<img width="805" alt="screen shot 2016-07-15 at 21 15 41" src="https://cloud.githubusercontent.com/assets/119117/16892208/5c80c72a-4ad1-11e6-872c-637fec22bd35.png">

Thanks a lot, any hint would be appreciated! Cheers!

**Comment by Glavin001** [comment]
Hmm I'm not sure at first glance what is causing the issue. Would you be able to create a small demo demonstrating this issue that I could play around with and debug? Thanks!

**Comment by benoror** [comment]
@Glavin001 got it 🐛 : https://ember-twiddle.com/2b4153485490b0f472a959528cf105b7?openFiles=routes.test.js%2C

To reproduce it you can navigate to `test` route, then to `other` and back to `test`

**Comment by benoror** [comment]
@Glavin001 sorry, did you have a chance to check it out?

**Comment by Glavin001** [comment]
~~I haven't yet. Thank you for reminder though. I'll try to today or tomorrow. If something comes up, feel free to ping me again. Thanks!~~

I was unable to get the Ember-Twiddle to work.
![image](https://cloud.githubusercontent.com/assets/1885333/16963054/dc0a2f1c-4dca-11e6-81a6-325628bbe8b8.png)

Could you double check it is working and reproduces the error, and maybe provide more instructions for how to use Ember-Twiddle. Ember-Twiddle is a great idea, thanks for sharing!

**Comment by benoror** [comment]
Weird, it's working on my side:

![img](http://g.recordit.co/n67MSbRVPB.gif)

**Comment by Glavin001** [comment]
Working now! Not sure why it was not before. And I can reproduce with this. Thanks!

**Comment by Glavin001** [comment]
So after playing around with some breakpoints: at some point the `json` property of `json-editor` component is set to `null` and calling `null.match` generates this error.

If you find a way to fix it, please let me know! Hopefully I'll have time to take another look this weekend. Thanks.

**Comment by benoror** [comment]
Cool, glad you could reproduce it. This is part of a [weekend project as well](https://github.com/benoror/ember-postgrest-dynamic-ui), therefore I will try to fix it in the weekend too.

Thanks and have a nice day!
