### ISSUE TITLE
How to override the change/onChange hook?

### ISSUE THREAD

**Issue by arnaudbesnier** [Glavin001/ember-jsoneditor#14]
I didn't found a way to attach a specific behaviour on JSON change.
Maybe you know an option for that?

Thank you 👍 

By the way, it seems that some options used in the ember wrapper are deprecated:

<img width="412" alt="screen shot 2016-09-20 at 18 36 34" src="https://cloud.githubusercontent.com/assets/664261/18679821/959a6006-7f61-11e6-9fbe-eddfc61f7c8c.png">

**Comment by maxwondercorn** [comment]
There is a new release that documents passing actions to component that will fire with the onChange and onError events.  The pull will happen soon, not sure how long before the NPM package will be updated.

Also, the options warnings have been fixed. 

Also, the warnings
